version: "3"



services:

  postgresdb:
    image: postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks: ['mynetwork']

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    networks: [ 'mynetwork' ]


networks: {mynetwork: {}}